# Generated by Django 6.0.2 on 2026-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_carerprofile_carer_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedRunState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
