# Generated by Django 6.0.2 on 2026-03-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_carerprofile_carer_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('name', 'Name'), ('relationship', 'Relationship')], max_length=20)),
                ('user_answer', models.CharField(blank=True, max_length=100)),
                ('expected_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('family_friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_attempts', to='user.familyfriend')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_attempts', to='user.patientprofile')),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
    ]
